reboot_device:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: grandstream_home

sleep_device:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: grandstream_home

wake_device:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: grandstream_home

shutdown_device:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: grandstream_home

unlock_door:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: grandstream_home
          manufacturer: Grandstream
    door_id:
      required: false
      default: 0
      selector:
        select:
          options:
            - label: "All doors"
              value: "0"
            - label: "Door 1"
              value: "1"
            - label: "Door 2"
              value: "2"

reset_all_alarms:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: grandstream_home
          manufacturer: Grandstream
